### ISSUE TITLE
Login workflow

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#1]
This is an overarching "epic" issue for the login workflow. The checklist links to individual issues.

-----

Description: As a user, I want to be able to login to my Ghost blog.

Although Ghost [doesn't have an official public API yet][1], it is possible to use the internal API by masquerading as the Ghost web client. I realize that it could change at any time without any warning whatsoever, but the hope is that it probably won't. That way when the official OAuth API is released it'll be easier to port this app (hopefully just an API version change and a few minor tweaks).

A typical login request / response in Ghost 0.5.7 looks like this (abbreviated):

Request (when fetching access token using a password):
```
POST /ghost/api/v0.1/authentication/token HTTP/1.1
Host: blog.example.com
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=<username>&password=<password>&client_id=ghost-admin
```

Request (when fetching access token using a refresh token):
```
POST /ghost/api/v0.1/authentication/token HTTP/1.1
Host: blog.example.com
Accept: application/json, text/javascript, */*; q=0.01
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=<refresh_token>&client_id=ghost-admin
```

Response:
```
HTTP/1.1 200 OK
Content-Type: application/json
Cache-Control: no-store
Pragma: no-cache

{
  "access_token": "<access_token>",
  "refresh_token": "<refresh_token>",     // absent when requested grant_type is "refresh_token"
  "expires_in": 3600,
  "token_type":"Bearer"
}
```

-----

Checklist:

- [x] Login form (fields for blog URL, username, password)
- [x] Login with access token (valid only for 1 hour, as of Ghost 0.5.7)
- [x] [Use refresh token to get a new access token every hour](https://github.com/vickychijwani/spectre/issues/2)
- [x] [Error handling (wrong password, invalid URL, etc)](https://github.com/vickychijwani/spectre/issues/4)
- [x] [Allow logout](https://github.com/vickychijwani/spectre/issues/13)

[1]: https://github.com/TryGhost/Ghost/issues/4004
