### ISSUE TITLE
Ghost 1.0

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#162]
Ghost 1.0 is releasing ~this month~, which means big breaking changes are imminent. I'm tracking all of the potential changes on this wiki page: https://github.com/vickychijwani/quill/wiki/Changes-for-Ghost-1.0. Specific todos will be added to this issue as they are formulated.

All work for this issue is happening in the `wip-ghost-1.0` branch.

### Mandatory changes

- [x] **GhostAuth**: this is going to be the default auth mechanism starting from 1.0. Since there doesn't seem to be an official way to add new OAuth clients atm, we'll have to still masquerade as Ghost Admin (like we do now). (**UPDATE**: Ghost Auth is disabled in Ghost now, apparently it will not ship in 1.0. See TryGhost/Ghost#8342.)
   - [x] **Re-authenticate on token expiry**
- [x] **Password auth**: the old auth mechanism will *also* be supported by Ghost, so we must have compatibility with password auth as well.
   - [x] **Re-authenticate on token expiry**
- [x] **Configuration endpoint schema changed**: the new schema for the (now public) `/configuration/` endpoint uses a typed-JSON dictionary, where the values can be bools, strings, or even objects.
- [x] **Token expiry increased**: access token expires after 30 days and refresh token after 180 days; refresh token expiry is delayed each time the access token is refreshed, so we should just get rid of `hasRefreshTokenExpired` and, indeed, `hasAccessTokenExpired` since the expiry times are very long. (note: this change is also included in Ghost 0.11.5 LTS)
- [x] **Data model changes**:
   - [x] **Numeric sequential IDs to String UUIDs**: Remove all instances where we're relying on the numeric nature of IDs (e.g., Comparator for sorting posts).
   - [x] **`markdown` field removed, superseded by `mobiledoc` field**: - see [comment below](#issuecomment-306276439) and [these](https://github.com/TryGhost/Ghost/issues/8479) [issues](https://github.com/TryGhost/Ghost/issues/8141)
   - [x] **`post.image` field renamed to `feature_image`**
   - [x] **`user.image` field renamed to `profile_image`**
   - [x] **Database migration**: probably just drop the database if it's at v3? Since we won't support Ghost 0.x.
- [x] **File storage permanently enabled**: It looks like file storage will always be available in Ghost 1.x, so the `fileStorage: true/false` config option is going away.
- [x] **Showdown replaced with markdown-it**: Changes enumerated [here](https://github.com/TryGhost/Ghost/commit/5d868d14ad6adc386a65f8f806154bed0fc24e6c).
- [ ] **Collision detection for edits?** - are there any changes requires for this? (ref: TryGhost/Ghost#5599 and the 2 associated PRs)

### Bugs

- [ ] **Memory leak on login screen**

### Optional changes

- [x] **Notify the user if they're using Ghost 0.x and we expect 1.x**: ask them to upgrade their blog, or to download the old app version for Ghost 0.x from the Play Store (as a separate app, "Quill for Ghost v0", which will not receive further updates)
- [x] **Upload APK for Ghost 0.x with different app id**
- [x] **Persistence overhaul**: Since a significant database change is needed for this anyway, this would be a good time to [rework the Realm storage architecture](https://github.com/vickychijwani/quill/wiki/Quill-v2#persistence-architecture) in preparation for #148 by storing each blog's data in a separate Realm file.
    - [x] Preserve the data Realm in the case where, e.g., credentials expire
    - [x] Delete the data Realm when a blog is removed (i.e., logged out)
- [x] **Drop API 15 support** - #101
- [x] **Add a link on the login screen to get help for login issues** - maybe also link to Ghost setup docs at https://docs.ghost.org/
- [x] **Analytics**: Especially successful and failed user logins + users who were rejected because they are not on Ghost 1.0
- [ ] **Crashlytics logging**: Especially during login

### Misc stuff

- [x] Test schema migration
- [x] Tablet layouts for login
- [x] Test token / auth code expiry
- [ ] Update Play Store listing to reflect these changes and maybe drop the warnings about stability

**Comment by kirrg001** [comment]
Hey @vickychijwani 👋

This is Kate from Ghost.  It's very exciting for us to see how much you care about the Ghost `1.0` changes. Very impressive! Our goal is to release the beta on Thursday. It's finally happening 😝

I wanted to share some details about our [mobiledoc editor](https://github.com/TryGhost/Ghost-Admin/tree/master/lib/gh-koenig).

The initial plan was to ship the new mobiledoc editor with `1.0`, but the complexity of edge cases and the wish to finally release `1.0` forced us to revert the editor for now. Instead we have added [SimpleMDE](https://github.com/sparksuite/simplemde-markdown-editor), a new and better markdown editor, which fills this gap for now. 

**But the idea is still to ship the mobiledoc editor as soon as possible**. And that's why we decided to keep the mobiledoc post field and [mobiledoc format](https://github.com/bustle/mobiledoc-kit#usage), to be able to switch to mobiledoc easily.

That means:
- the markdown field in the post model was removed
- the Ghost API expects mobildoc format with a single markdown card (which contains markdown content)

#### Format in Ghost `0.11.x`
```
{ 
  `markdown`: '## headline'
}

```
#### Format in Ghost `1.0`
```
{
  "version":"0.3.1",
  "markups":[],
  "atoms":[],
  "cards":[
     ["card-markdown", {
         "cardName": "card-markdown", 
         "markdown": "# headline"
      }]
    ],
 "sections":[[10,0]]   // a static value for now
}
```

External clients (like quill) are required to send this format for `1.0`.

We thought about keeping the ability to send/receive `markdown` to/from the Ghost API, which then get's transformed into mobiledoc format, which would be easier for external clients like quill. But we would like to wait how complicated this requirement is and that the reason keeping the mobiledoc format is understood from our external clients.

Thanks so much for quill!
If you have any questions, come say hello on [slack](https://slack.ghost.org)!

**Comment by vickychijwani** [comment]
Hi @kirrg001 🙂 

I'm looking forward to the 1.0 beta!

Your comment clarifies the changes I would need to make, and having visibility into the Ghost team's thought process provides useful context. I'll need to dig deeper into the mobiledoc format to understand what all those fields mean, but this is a great starting point. Thank you!

I'll reach out via Slack for any questions.
