### ISSUE TITLE
Create / edit post workflow

### ISSUE THREAD

**Issue by vickychijwani** [vickychijwani/quill#5]
This is an overarching "epic" issue for the create / edit post workflow. The checklist links to individual issues.

-----

As a user, I want to be able to:

- Create drafts and save them
- Edit drafts and save them
- Publish drafts
- Edit published posts
- Unpublish posts

### Post slug creation

```http
GET /ghost/api/v0.1/slugs/post/My%20awesome%20post%20title/
Authorization: Bearer <access_token>

200 OK
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Content-Type: application/json; charset=utf-8
ETag: W/"20-95717991"

{
  "slugs": [{
    "slug": "my-awesome-post-title"
  }]
}
```

### Draft creation

```http
POST /ghost/api/v0.1/posts/?include=tags
Authorization: Bearer <access_token>
Content-Type: application/json; charset=UTF-8

{  
  "posts":[  
    {  
      "title":"Blah blah",
      "slug":"blah-blah",
      "markdown":"",
      "image":null,
      "featured":false,
      "page":false,
      "status":"draft",
      "language":"en_US",
      "meta_title":null,
      "meta_description":null,
      "author":"1",
      "published_by":null,
      "tags":[  
        {  
          "uuid":null,
          "name":"c++",
          "slug":null,
          "description":null,
          "meta_title":null,
          "meta_description":null,
          "image":null,
          "hidden":false,
          "post_count":null
        },
        {  
          "uuid":null,
          "name":"another-tag",
          "slug":null,
          "description":null,
          "meta_title":null,
          "meta_description":null,
          "image":null,
          "hidden":false,
          "post_count":null
        }
      ]
    }
  ]
}

201 Created
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
Location: /ghost/api/v0.1/posts/2/?status=draft
Content-Type: application/json; charset=utf-8

{  
  "posts":[  
    {  
      "id":2,
      "uuid":"2bf55004-6c3b-4d8b-9929-31bf46c1b620",
      "title":"Blah blah",
      "slug":"blah-blah",
      "markdown":"",
      "html":"",
      "image":null,
      "featured":false,
      "page":false,
      "status":"draft",
      "language":"en_US",
      "meta_title":null,
      "meta_description":null,
      "created_at":"2015-02-18T10:36:36.647Z",
      "created_by":1,
      "updated_at":"2015-02-18T10:36:36.647Z",
      "updated_by":1,
      "published_at":null,
      "published_by":null,
      "tags":[  
        {  
          "id":2,
          "uuid":"6105741a-d031-4064-99b1-ef4e9a2953c6",
          "name":"c++",
          "slug":"c",
          "description":null,
          "image":null,
          "hidden":false,
          "meta_title":null,
          "meta_description":null,
          "created_at":"2015-02-18T10:36:36.695Z",
          "created_by":1,
          "updated_at":"2015-02-18T10:36:36.695Z",
          "updated_by":1,
          "parent":null
        },
        {  
          "id":3,
          "uuid":"1ab0ec4a-567a-48ab-824c-6665894e83ab",
          "name":"another-tag",
          "slug":"another-tag",
          "description":null,
          "image":null,
          "hidden":false,
          "meta_title":null,
          "meta_description":null,
          "created_at":"2015-02-18T10:36:36.758Z",
          "created_by":1,
          "updated_at":"2015-02-18T10:36:36.758Z",
          "updated_by":1,
          "parent":null
        }
      ],
      "author":1,
      "url":"/blah-blah/"
    }
  ]
}
```

### Publish draft

Make a PUT request to `/ghost/api/v0.1/posts/2/?include=tags` with the post payload and `post.status` set to `published`.

### Update published post
```http
PUT /ghost/api/v0.1/posts/<post_id>/?include=tags
Authorization: Bearer <access_token>
Content-Type: application/json; charset=UTF-8

{
  "posts": [{
    "title": "Post title",
    "slug": "post-slug",
    "markdown": "Here's some _Markdown_ **text**!",
    "image": "",
    "featured": false,
    "page": false,
    "status": "published",
    "language": "en_US",
    "meta_title": null,
    "meta_description": null,
    "updated_at": "2015-01-12T19:32:44.182Z",
    "published_at": "2014-11-06T20:28:00.364Z",
    "author": "1",
    "published_by": "1",
    "tags": [{
      "id": "8",
      "uuid": "025a5d49-b6f3-4941-b25c-676c3320684e",
      "name": "c++",
      "slug": "c-2",
      "description": null,
      "parent_id": null,
      "meta_title": null,
      "meta_description": null,
      "image": null
    }]
  }]
}

200 OK
Content-Type: application/json; charset=utf-8
Cache-Control: no-cache, private, no-store, must-revalidate, max-stale=0, post-check=0, pre-check=0
X-Cache-Invalidate: /, /page/*, /rss/, /rss/*, /tag/*, /author/*, /sitemap-*.xml, /post-slug/

<same as request body, except one additional field: html generated from markdown>
```

-----

Checklist:

- [x] [Post editor (simple text field, no UI controls, no HTML preview)](https://github.com/vickychijwani/spectre/issues/6)
- [x] [Markdown preview in post editor](https://github.com/vickychijwani/spectre/issues/7)
- [x] [Allow creating new drafts and saving them](https://github.com/vickychijwani/spectre/issues/29)
- [x] [Allow editing post title in editor](https://github.com/vickychijwani/spectre/issues/14)
- [x] [Allow adding / removing tags in post editor](https://github.com/vickychijwani/spectre/issues/10)
- [x] [Allow saving drafts / published posts](https://github.com/vickychijwani/spectre/issues/11)
- [x] [Allow publishing / unpublishing posts](https://github.com/vickychijwani/spectre/issues/12)
- [x] [Image uploads in post editor](https://github.com/vickychijwani/spectre/issues/9)
